# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/jenkins_codedeploy_test

    environment:

      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      SBT_VERSION: 1.0.4

    steps:
      - run: echo 'export ARTIFACT_BUILD=circleci-deploy-test-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run:
          name: sbt バイナリを取得
          command: |
            sudo apt update && sudo apt install -y curl
            sudo curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            sudo dpkg -i sbt-$SBT_VERSION.deb
            sudo rm sbt-$SBT_VERSION.deb
            sudo apt-get update
            sudo apt-get install -y sbt python-pip git
            sudo pip install awscli
            sudo apt-get clean && sudo apt-get autoclean

      - checkout
      # Download and cache dependencies
      - restore_cache:
          key: sbt-cache

      # compile
      - run:
          name: sbt compile (jarファイル作成)
          command: cat /dev/null | sbt clean assembly
      - run:
          name: zipファイル作成
          command: |
              cd ../jenkins_codedeploy_test
              zip -r circleci-deploy-test ./*
      - store_artifacts:
          path: circleci-deploy-test.zip
          destination: circleci-deploy-test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - deploy:
          name: Deploy to S3
          command: |
              sudo mv circleci-deploy-test.zip $CIRCLE_ARTIFACTS/$ARTIFACT_BUILD
              aws s3 cp $CIRCLE_ARTIFACTS/$ARTIFACT_BUILD s3://circleci-deploy-test/scala.helloworld/ --metadata {\"git_sha1\":\"$CIRCLE_SHA1\"}

      - deploy:
          name: Deploy to EC2
          command: |
              aws deploy create-deployment \
                  --application-name circleci-deploy-test \
                  --deployment-group-name circleci-deploy-test-g \
                  --s3-location bucket="circleci-deploy-test",bundleType="zip",key="scala.helloworld/$ARTIFACT_BUILD" \
                  --region ap-northeast-1
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
        filters:
          branches:
            only: 
              - master