# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/jenkins_codedeploy_test

    environment:

      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      SBT_VERSION: 1.0.4

    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run:
          name: sbt バイナリを取得
          command: |
            sudo apt update && apt install -y curl
            sudo curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            sudo dpkg -i sbt-$SBT_VERSION.deb
            sudo rm sbt-$SBT_VERSION.deb
            sudo apt-get update
            sudo apt-get install -y sbt python-pip git
            pip install awscli
            sudo apt-get clean && apt-get autoclean

      - checkout
      # Download and cache dependencies
      - restore_cache:
          key: sbt-cache

      # compile
      - run:
          name: sbt compile
          command: cat /dev/null | sbt clean assembly dist
      - store_artifacts:
          path: target/universal/jenkins_codedeploy_test.zip
          destination: jenkins_codedeploy_test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
